plugins {
    id 'com.android.application'
    id 'kotlin-android'
}

android {
    compileSdk 36

    applicationVariants.all { variant ->
        variant.outputs.all {
            outputFileName = "${defaultConfig.applicationId}_${defaultConfig.versionName}_${variant.buildType.name}.apk"
        }
    }

    signingConfigs {
        release {
            storeFile file("${rootDir}/keystore.key")
            storePassword System.getenv("ANDROID_STORE_PASSWORD")
            keyAlias "key0"
            keyPassword System.getenv("ANDROID_KEY_PASSWORD")
        }
    }

    defaultConfig {
        applicationId "io.github.xposed.androidspoofer"
        minSdk 34
        targetSdk 36
        versionCode 1
        versionName "1.0.0"
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            if (System.getenv("ANDROID_STORE_PASSWORD")) {
                signingConfig signingConfigs.release
            }
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    lint {
        checkReleaseBuilds false
    }
    kotlinOptions {
        jvmTarget = '17'
    }
    namespace 'io.github.xposed.androidspoofer'
    buildFeatures {
        buildConfig true
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.17.0'
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.webkit:webkit:1.14.0'

    // Appset ID
    implementation 'com.google.android.gms:play-services-appset:16.1.0'

    // Ad ID
    implementation "com.google.android.gms:play-services-ads-identifier:18.2.0"

    // Xposed API
    compileOnly files('libs/api-82.jar')
    compileOnly files('libs/api-82-sources.jar')
}