name: Deploy

on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Cache Docker layers
        uses: actions/cache@v4
        continue-on-error: true
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Build
        run: |
          ANDROID_STORE_PASSWORD=${{ secrets.ANDROID_STORE_PASSWORD }} \
            ANDROID_KEY_PASSWORD=${{ secrets.ANDROID_KEY_PASSWORD }} \
            DOCKER_BUILD_ARGS="\
              --cache-from type=local,src=/tmp/.buildx-cache \
              --cache-to type=local,dest=/tmp/.buildx-cache-new \
              " \
            ./build.sh

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: output
