name: Build

on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Setup Cache
        uses: actions/cache@v4
        continue-on-error: true
        with:
          key: ${{ runner.os }}-${{ hashFiles('Dockerfile') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('Dockerfile') }}
          path: |
            cache

      - name: Build
        run: |
          mkdir cache || true

          ANDROID_STORE_PASSWORD=${{ secrets.ANDROID_STORE_PASSWORD }} \
            ANDROID_KEY_PASSWORD=${{ secrets.ANDROID_KEY_PASSWORD }} \
            DOCKER_BUILD_ARGS="\
              --cache-from type=local,src=cache/buildx \
              --cache-to type=local,dest=cache/buildx-new \
              " \
            ./build.sh

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move Docker cache
        run: |
          rm -rf cache/buildx
          mv cache/buildx-new cache/buildx

      - name: Upload App Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: output/apk

      - name: Upload Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: output/reports
