name: Deploy

on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
      - name: Build
        run: |
          ANDROID_STORE_PASSWORD=${{ secrets.ANDROID_STORE_PASSWORD }} \
            ANDROID_KEY_PASSWORD=${{ secrets.ANDROID_KEY_PASSWORD }} \
            ./build.sh
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: output
